[build]
  command = "npm run install:all && npm run build"
  publish = "client/dist"

[functions]
directory = "server/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200